// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `DeviceEndpointPrxHolder.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.oss.teamwork.teamshare.communication.zerocice;

public final class DeviceEndpointPrxHolder
{
    public
    DeviceEndpointPrxHolder()
    {
    }

    public
    DeviceEndpointPrxHolder(DeviceEndpointPrx value)
    {
        this.value = value;
    }

    public DeviceEndpointPrx value;
}
