/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.oss.teamshare.communication.swift;

public class swiftJNI {
  public final static native void Start(String jarg1, String jarg2, String jarg3, String jarg4);
  public final static native String GetRootHash(String jarg1);
}
