#!/usr/bin/env bash

CP=target/teamshare-1.0-SNAPSHOT.jar:target/jackson-core-2.1.3.jar:target/joda-time-2.1.jar:target/zeroc-ice-3.4.jar:target/jackson-databind-2.1.3.jar:target/junit-4.11.jar:target/log4j-api-2.0-beta4.jar:target/log4j-core-2.0-beta4.jar:target/commons-lang3-3.1.jar:target/jackson-annotations-2.1.2.jar:target/hamcrest-core-1.3.jar

LD_LIBRARY_PATH=lib:. java $@ -cp $CP com.oss.teamshare.Main
