// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_DeviceEndpointDel.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.oss.teamshare.communication.zerocice;

public interface _DeviceEndpointDel extends Ice._ObjectDel
{
    void notifyRevision(String uri, String swarmId, String seederAddress, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
