// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_DeviceEndpointOperations.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.oss.teamshare.communication.zerocice;

public interface _DeviceEndpointOperations
{
    void notifyRevision(String teamId, String filename, String swarmId, Ice.Current __current);

    String getLatestRevisionHash(String teamId, String filename, Ice.Current __current);
}
