// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `DeviceEndpointPrxHelper.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.oss.teamshare.communication.zerocice;

public final class DeviceEndpointPrxHelper extends Ice.ObjectPrxHelperBase implements DeviceEndpointPrx
{
    public void
    notifyRevision(String uri, String swarmId)
    {
        notifyRevision(uri, swarmId, null, false);
    }

    public void
    notifyRevision(String uri, String swarmId, java.util.Map<String, String> __ctx)
    {
        notifyRevision(uri, swarmId, __ctx, true);
    }

    private void
    notifyRevision(String uri, String swarmId, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        int __cnt = 0;
        while(true)
        {
            Ice._ObjectDel __delBase = null;
            try
            {
                __delBase = __getDelegate(false);
                _DeviceEndpointDel __del = (_DeviceEndpointDel)__delBase;
                __del.notifyRevision(uri, swarmId, __ctx);
                return;
            }
            catch(IceInternal.LocalExceptionWrapper __ex)
            {
                __handleExceptionWrapper(__delBase, __ex);
            }
            catch(Ice.LocalException __ex)
            {
                __cnt = __handleException(__delBase, __ex, null, __cnt);
            }
        }
    }

    private static final String __notifyRevision_name = "notifyRevision";

    public Ice.AsyncResult begin_notifyRevision(String uri, String swarmId)
    {
        return begin_notifyRevision(uri, swarmId, null, false, null);
    }

    public Ice.AsyncResult begin_notifyRevision(String uri, String swarmId, java.util.Map<String, String> __ctx)
    {
        return begin_notifyRevision(uri, swarmId, __ctx, true, null);
    }

    public Ice.AsyncResult begin_notifyRevision(String uri, String swarmId, Ice.Callback __cb)
    {
        return begin_notifyRevision(uri, swarmId, null, false, __cb);
    }

    public Ice.AsyncResult begin_notifyRevision(String uri, String swarmId, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_notifyRevision(uri, swarmId, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_notifyRevision(String uri, String swarmId, Callback_DeviceEndpoint_notifyRevision __cb)
    {
        return begin_notifyRevision(uri, swarmId, null, false, __cb);
    }

    public Ice.AsyncResult begin_notifyRevision(String uri, String swarmId, java.util.Map<String, String> __ctx, Callback_DeviceEndpoint_notifyRevision __cb)
    {
        return begin_notifyRevision(uri, swarmId, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_notifyRevision(String uri, String swarmId, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __notifyRevision_name, __cb);
        try
        {
            __result.__prepare(__notifyRevision_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__os();
            __os.writeString(uri);
            __os.writeString(swarmId);
            __os.endWriteEncaps();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_notifyRevision(Ice.AsyncResult __result)
    {
        __end(__result, __notifyRevision_name);
    }

    public static DeviceEndpointPrx
    checkedCast(Ice.ObjectPrx __obj)
    {
        DeviceEndpointPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (DeviceEndpointPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    DeviceEndpointPrxHelper __h = new DeviceEndpointPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static DeviceEndpointPrx
    checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        DeviceEndpointPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (DeviceEndpointPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    DeviceEndpointPrxHelper __h = new DeviceEndpointPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static DeviceEndpointPrx
    checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        DeviceEndpointPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    DeviceEndpointPrxHelper __h = new DeviceEndpointPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static DeviceEndpointPrx
    checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        DeviceEndpointPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    DeviceEndpointPrxHelper __h = new DeviceEndpointPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static DeviceEndpointPrx
    uncheckedCast(Ice.ObjectPrx __obj)
    {
        DeviceEndpointPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (DeviceEndpointPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                DeviceEndpointPrxHelper __h = new DeviceEndpointPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static DeviceEndpointPrx
    uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        DeviceEndpointPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            DeviceEndpointPrxHelper __h = new DeviceEndpointPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::com::oss::teamshare::communication::zerocice::DeviceEndpoint"
    };

    public static String
    ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM
    __createDelegateM()
    {
        return new _DeviceEndpointDelM();
    }

    protected Ice._ObjectDelD
    __createDelegateD()
    {
        return new _DeviceEndpointDelD();
    }

    public static void
    __write(IceInternal.BasicStream __os, DeviceEndpointPrx v)
    {
        __os.writeProxy(v);
    }

    public static DeviceEndpointPrx
    __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            DeviceEndpointPrxHelper result = new DeviceEndpointPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }
}
