// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `DeviceEndpointPrx.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.oss.teamshare.communication.zerocice;

public interface DeviceEndpointPrx extends Ice.ObjectPrx
{
    public void notifyRevision(String uri, String swarmId);

    public void notifyRevision(String uri, String swarmId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_notifyRevision(String uri, String swarmId);

    public Ice.AsyncResult begin_notifyRevision(String uri, String swarmId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_notifyRevision(String uri, String swarmId, Ice.Callback __cb);

    public Ice.AsyncResult begin_notifyRevision(String uri, String swarmId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_notifyRevision(String uri, String swarmId, Callback_DeviceEndpoint_notifyRevision __cb);

    public Ice.AsyncResult begin_notifyRevision(String uri, String swarmId, java.util.Map<String, String> __ctx, Callback_DeviceEndpoint_notifyRevision __cb);

    public void end_notifyRevision(Ice.AsyncResult __result);
}
