package com.oss.teamwork.teamshare.messaging;

public enum MessageType {
	INVITATION,
	INVITATION_ACCEPTANCE,
	INVITATION_REFUSAL,
	OWNERSHIP_TRANSFER,
	OWNERSHIP_TRANSFER_ACCEPTANCE,
	OWNERSHIP_TRANSFER_REFUSAL;
}
